AllCops:
  Exclude:
    - 'spec/dummy_app/bin/**/*'
    - 'spec/dummy_app/db/schema.rb'
    - 'spec/dummy_app/tmp/**/*'
  Rails:
    Enabled: true
Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false
StringLiterals:
  EnforcedStyle: double_quotes
